@local=localhost:8452
@lambda=asdf

@baseUrl={{local}}


### get all reminders
GET http://{{baseUrl}}/reminders/v1
Content-Type: application/json

### Get a reminder by Id
GET http://{{baseUrl}}/reminders/v1/593db991-72d5-4688-a4e2-fb22da5d7a3e
Content-Type: application/json

### Create a Reminder
POST http://{{baseUrl}}/reminders/v1
Content-Type: application/json

{
  "title": "do laundry"
}

### Delete a Reminder
DELETE http://{{baseUrl}}/reminders/v1/5cb371a8-af30-48b7-bc62-45c30815955f
Content-Type: application/json

